sql:
  url: 127.0.0.1
  port: 3306
  username: adminstrator
  password: pass
  database: minecraft
default-mayor-permissions:
  -essentials.gamemode
  -essentials.fly
  -coreprotect.lookup
  -tperms.give.essentails.feed
  -tperms.give.coreprotect.lookup