sql:
  url: 127.0.0.1
  port: 3306
  username: adminstrator
  password: pass
  database: minecraft
default-mayor-permissions:
  - inspect
  - rollback
  - lookup
  - restore
  - ban
  - mute
  - unmute
  - unban
  - fly
  - groupnew
  - groupdelete
  - groupadd
  - groupremove
  - playeradd
  - playerremove